services:
  - type: web
    name: punta-espada
    runtime: docker
    plan: free
    region: ohio
    dockerfilePath: ./Dockerfile
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: punta-espada-db
          property: connectionString

databases:
  - name: punta-espada-db
    plan: free
    databaseName: punta
    user: punta
    region: ohio
